name: Run calculation
on:
  issues:
    types: [opened]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Set env
        run: echo "GITHUB_API_TOKEN=${{secrets.MY_GH_TOKEN}}" >> $GITHUB_ENV
      - name: Run the command
        run: |
          cd .github/actions/calculate
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          python3 exec.py
        env:
          COMMAND_CONTEXT: ${{ toJSON(github) }}
          ORG: "psecio"
          PROJECT_ID: "1"